version: '3.8'

services:
  postgreSQL:
    image: postgres:16-alpine
    restart: no
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: graphql_demo
      POSTGRES_PASSWORD: admin123
